<a href="https://colab.research.google.com/github/joohoshin/MLDL_Basic/blob/master/3_2_Numpy_%EA%B8%B0%EC%B4%88_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열 자동 생성
* random을 통해서 자동으로 생성가능함
* randint(start, end, size = (row size, column size)) 형태로 사용 (end는 포함되지 않음)

In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(0,10, size=(2,3))
print(arr1)

arr2 = np.random.randint(0,10, size = 10)
print(arr2)

[[7 4 0]
 [7 3 4]]
[3 5 3 4 2 0 8 8 1 0]


* rand(row size, column size)는 0~1 사이의 값을 랜덤 선택 (1은 미포함)


In [ ]:
arr3 = np.random.rand(5,3)
print(arr3)

[[0.13506137 0.74429129 0.79234368]
 [0.36866682 0.92896132 0.56316011]
 [0.06738341 0.61495675 0.92124939]
 [0.12153414 0.68831947 0.59615814]
 [0.27323113 0.55526047 0.70250251]]


In [ ]:
arr4 = np.random.rand(5,3)
print(arr4)

[[0.54890163 0.13012969 0.50730345]
 [0.80947023 0.86995128 0.9919448 ]
 [0.05885575 0.47590606 0.46764917]
 [0.82826764 0.89907778 0.30360596]
 [0.27291213 0.33055165 0.59864073]]


* 그 외에도 여러가지 행렬 연산 기능이 있음
* https://www.bogotobogo.com/python/python_numpy_matrix_tutorial.php

##### 주요 통계값
* 리스트와 마찬가지로 min(), count() 등 되며
* 평균 및 표준편차도 쉽게 구할 수 있다 mean(), std() 

In [ ]:
print(arr4.sum())
print(arr4.min())
print(arr4.max())
print(arr4.mean()) # 평균
print(arr4.std()) # 표준편차
print(arr4.var()) # 분산


8.093167944366154
0.058855748340324365
0.9919448018089624
0.5395445296244102
0.2807463837808541
0.07881853200602662


##### 특정 범위 가져오기
* arr[start:end:step]으로 특정 범위 데이터를 가져올 수 있다
  (end 는 미포함)
* 리스트와 동일함

In [ ]:
arr5 = np.random.randint(10, size = 10)
print(arr5)

[5 2 6 3 6 1 1 7 6 7]


In [ ]:
arr5[:5] 

array([5, 2, 6, 3, 6])

In [ ]:
arr5[1:3]

array([2, 6])